### ISSUE TITLE
Results quality

### ISSUE THREAD

**Issue by pabloppp** [lzhbrian/SinGAN-pytorch#1]
Hi @lzhbrian ! 

Would you be so kind to add some of your resulting images to the readme?
I tried running your code but the results that I get are still pretty far from those from the paper :/ 
Is this still a limitation of your code? (as it's a WIP) or are you able to get the same results as in the paper?
I've been trying to replicate the paper as well with poor results for a few weeks now, then I saw your code and hoped that your results were better than mine :S

Thanks!

**Comment by lzhbrian** [comment]
I also have problems reimplementing this paper. My results are also far from expected.
I do not know where the problem is. I think I have noticed all the details described in the paper.
What do you think? Is my implementation any different with yours?

<img width="640" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/12770792/59264867-a3952180-8c76-11e9-91ef-4ba11f18e322.png">

**Comment by pabloppp** [comment]
My original implementation was very similar :/ 
I think the main differences were that I was not fixing the std of the noise and I was adding a tanh activation to the generator, my results were pretty similar though :( 
Since I saw your code I tried changing those things in my implementation to match yours + a few small things, and here are my results from the 5th GAN level (I'm not even training the full model since the results I get are obviously not good enough)

![image](https://user-images.githubusercontent.com/4237014/59268810-cd861e00-8c4d-11e9-9221-1f60efc809ed.png)

I contacted Tamar Rott, one of the authors of the paper, told her what I was doing and she told me everything seemed right and that she'll be publishing code in the next weeks, so that's something (I even asked to have a video call, I hope she accepts, maybe you can join as well as you're also trying to replicate it). 
Anyway I feel like the paper is lacking a lot of important details and is very hard to replicate T__T 
I'm still changing things in my implementation and trying to make it work XD

**Comment by lzhbrian** [comment]
I also contacted the author and asked a few details.
However, after I did all the details she mentioned, the results are still bad.
Maybe the only promising solution is waiting for the official code release, I think there might be some tricks that seem trivial and not mentioned by the author,  yet are actually very important.
If you plan on a video call, please let me know the time :)

Thanks!

**Comment by pabloppp** [comment]
Looks like someone else implemented the code in PyTorch with quite good results https://github.com/FriedRonaldo/SinGAN
